name: Publish to NuGet

on:
  push:
    branches:
      - main
  
  # Allow mannually trigger 
  workflow_dispatch: 
     
jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
  
   - name: Setup .NET SDK
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: '9.0.x'

   - name: Build project
     run: dotnet build src/BlazorSseClient/BlazorSseClient.csproj --configuration Release

   - name: Create package
     run: dotnet pack src/BlazorSseClient/BlazorSseClient.csproj --configuration Release

   - name: Publish main package to NuGet
     run: dotnet nuget push src/BlazorSseClient/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

   - name: Publish symbols package to NuGet
     run: dotnet nuget push src/BlazorSseClient/bin/Release/*.snupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
